--MINIPRJ[회원목록]
DROP TABLE ECO_MEMBER;
CREATE TABLE ECO_MEMBER(
    ID VARCHAR2(100) PRIMARY KEY
    , PWD VARCHAR2(100) NOT NULL
    , NAME VARCHAR2(100) NOT NULL
    , NICK VARCHAR2(100) NOT NULL UNIQUE
    , GENDER CHAR(1) CHECK(GENDER IN('M','F')) NOT NULL
    , PHONE VARCHAR2(100) NOT NULL UNIQUE
    , BANK VARCHAR2(100) NOT NULL
    , ACCOUNT VARCHAR2(100) NOT NULL UNIQUE
    , POINT NUMBER DEFAULT 0 NOT NULL
    , ADDEDPOINT NUMBER DEFAULT 0 NOT NULL
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
    ,RANK VARCHAR2(20) DEFAULT '씨앗' NOT NULL
    , QUIT_YN CHAR(1) DEFAULT 'N' CHECK(QUIT_YN IN ('Y', 'N')) NOT NULL
);

COMMENT ON COLUMN ECO_MEMBER.ID IS '유저아이디'; 
COMMENT ON COLUMN ECO_MEMBER.PWD IS '유저비밀번호'; 
COMMENT ON COLUMN ECO_MEMBER.NAME IS '이름'; 
COMMENT ON COLUMN ECO_MEMBER.NICK IS '닉네임'; 
COMMENT ON COLUMN ECO_MEMBER.GENDER IS '성별'; 
COMMENT ON COLUMN ECO_MEMBER.PHONE IS '핸드폰번호'; 
COMMENT ON COLUMN ECO_MEMBER.BANK IS '은행명'; 
COMMENT ON COLUMN ECO_MEMBER.ACCOUNT IS '계좌번호'; 
COMMENT ON COLUMN ECO_MEMBER.POINT IS '적립금'; 
COMMENT ON COLUMN ECO_MEMBER.ADDEDPOINT IS '누적적립금'; 
COMMENT ON COLUMN ECO_MEMBER.ENROLL_DATE IS '가입시간'; 
COMMENT ON COLUMN ECO_MEMBER.RANK IS '등급'; 
COMMENT ON COLUMN ECO_MEMBER.QUIT_YN IS '탈퇴여부'; 

INSERT INTO ECO_MEMBER (ID, PWD, NAME, NICK, GENDER, PHONE, BANK, ACCOUNT) VALUES('TAEWON', '1234', 'YTW', 'WON', 'M', '01088062483', '우리', '19812278413');
SELECT * FROM ECO_MEMBER;