--MINIPRJ[등급표]
DROP TABLE RANKSYS;
CREATE TABLE RANKSYS(
    RANK VARCHAR(20) PRIMARY KEY 
    , MINPOINT NUMBER NOT NULL UNIQUE
    , MAXPOINT NUMBER NOT NULL UNIQUE
    , BONUS NUMBER NOT NULL UNIQUE
);

COMMENT ON COLUMN RANKSYS.RANK IS '등급'; 
COMMENT ON COLUMN RANKSYS.MINPOINT IS '최소기준치';
COMMENT ON COLUMN RANKSYS.MAXPOINT IS '최대기준치';
COMMENT ON COLUMN RANKSYS.BONUS IS '등급별혜택';

INSERT INTO RANKSYS VALUES ('씨앗', 0, 2999, 0);
INSERT INTO RANKSYS VALUES ('새싹', 3000, 14999, 10);
INSERT INTO RANKSYS VALUES ('가지', 15000, 49999, 30);
INSERT INTO RANKSYS VALUES ('열매', 50000, 149999, 60);
INSERT INTO RANKSYS VALUES ('꽃', 150000, 999999, 100);

SELECT * FROM RANKSYS;
