--MINIPRJ[포인트유동기록]
DROP TABLE HISTORY;
CREATE TABLE HISTORY(
    NO NUMBER PRIMARY KEY
    , ID VARCHAR2(100) NOT NULL
    , TIME_REPORT TIMESTAMP DEFAULT SYSDATE NOT NULL
    , POINT NUMBER DEFAULT 0 NOT NULL 
    , REPORT VARCHAR2(100)  NOT NULL 
);
COMMENT ON COLUMN HISTORY.NO IS '생성순서';
COMMENT ON COLUMN HISTORY.ID IS '유저아이디'; 
COMMENT ON COLUMN HISTORY.TIME_REPORT IS '기부또는적립금입출시간';
COMMENT ON COLUMN HISTORY.POINT IS '적립금입출내역';
COMMENT ON COLUMN HISTORY.REPORT IS '내역';

DROP SEQUENCE SEQ_HISTORY_NO;
CREATE SEQUENCE SEQ_HISTORY_NO;

SELECT * FROM HISTORY;

INSERT INTO HISTORY(NO, ID, POINT, REPORT) 
VALUES (SEQ_HISTORY_NO.NEXTVAL, 
'TAEWON', 
(SELECT CUPPOINT FROM CAFE  WHERE NAME = 'KFC' ),
'일회용 컵 반환' );