SELECT * FROM ECO_MEMBER;
SELECT * FROM HISTORY;

UPDATE ECO_MEMBER 
SET 
POINT = POINT + (SELECT CUPPOINT FROM CAFE WHERE NAME = 'KFC')
, ADDEDPOINT =ADDEDPOINT + (SELECT CUPPOINT FROM CAFE WHERE NAME = 'KFC')
WHERE ID = 'TAEWON'; 

INSERT INTO HISTORY(ID, POINT) 
VALUES (
(SELECT ID FROM ECO_MEMBER WHERE ID = 'TAEWON')
, (SELECT CUPPOINT FROM CAFE  WHERE NAME = 'KFC' ) );

SELECT ID FROM ECO_MEMBER WHERE NAME = 'YTW' AND PHONE = '01088062483';
